### ISSUE TITLE
Question about additional line artifact on sinogram domain

### ISSUE THREAD

**Issue by Eugene-JPI** [nghia-vo/sarepy#11]
Hi, 
Firstly, thanks for the great work.
I am working with CBCT which has lots of small-to-medium stripes on sinogram.
After applying Algorithm 6, 5, 3 or Algorithm 3 only, most of the small-to-medium disappears.
But new artifacts appears and below is the screen capture of the sinogram.
![image](https://github.com/user-attachments/assets/246c4fa8-1daf-4ae6-b01c-8b035561d2f6)
These blurring? lines are consistence for all the sinograms at exactly same position.
Wonder why these artifacts are made, and what should I do to remove or reduce them?

**Comment by nghia-vo** [comment]
Hi Eugene, it's the side effect of an interpolation method in Algorithm 6 for removing dead stripes (caused by dead pixels). Check Figure 6 of this tutorial: https://sarepy.readthedocs.io/toc/section3_1/section3_1_5.html . If your detector doesn't have many dead pixels, you can reduce the strength of Algorithm 6 by increasing snr to something 3.0, size to ~21. 
As Sarepy was deprecated, I would recommend to use these algorithms through [Algotom](https://algotom.readthedocs.io/en/latest/toc/api/algotom.prep.removal.html). I wrote instruction on how to clean data for cone-beam tomography here: https://algotom.readthedocs.io/en/latest/toc/section4/section4_4.html#for-cone-beam-tomography

In Algotom, you can use this method for parallel processing: https://algotom.readthedocs.io/en/latest/toc/api/algotom.util.utility.html#algotom.util.utility.parallel_process_slices
Example of usage:
https://algotom.readthedocs.io/en/latest/toc/section4/section4_5.html#performing-full-reconstruction

**Comment by Eugene-JPI** [comment]
Thanks for answering. 
I have installed algotom and is going to apply on the datasets following your instructions.
By the way, I have one more questions to ask. The below slices are the result of those sinograms reconstructed.
The first one is before applying sarepy and the second is after applying.
![image](https://github.com/user-attachments/assets/3ee6c128-ea68-479d-95f1-6c0ede4da47d)
![image](https://github.com/user-attachments/assets/47e3e50f-e062-4dde-a09c-cb9e1ec8bd5b)

After applying sarepy, those small-to-mediums are removed, but additional ring is generated.
I guess the cause is the bone nearby the generated ring.
I am going to try with different parameters and methods with and without for removal through Algotom, but before that I just wanted to ask for your insights.

**Comment by nghia-vo** [comment]
There's no ring artifact caused by a dead pixel in your data. Try not use algorithm 6. You can use the remove_based_sorting only with size~41

**Comment by Eugene-JPI** [comment]
Thank you so much for the help!
