### ISSUE TITLE
Possible to remove stripes from this type of images..

### ISSUE THREAD

**Issue by shalinsirwani** [nghia-vo/sarepy#6]
![112](https://user-images.githubusercontent.com/28221425/89887160-6ebe8a80-dbeb-11ea-8943-6f6a549d1d42.jpg)
![113](https://user-images.githubusercontent.com/28221425/89887171-72eaa800-dbeb-11ea-93bd-b0785a64f7bf.jpg)
![111](https://user-images.githubusercontent.com/28221425/89887181-75e59880-dbeb-11ea-9ca0-e33decc58fe5.jpg)

**Comment by nghia-vo** [comment]
These are streak artifacts caused by high-frequency features in the sinogram and less number of projections. Applying a low-pass filter to the sinogram before reconstruction can help to reduce these artifacts. Could you share your sinogram?

**Comment by shalinsirwani** [comment]
Sure
Porjections are upto 180 degrees well i don't know about **high-frequency features in the sinogram**.
these are some of three sinogram with their Filtered Bck Projections.

**Sino**

![ sino 157](https://user-images.githubusercontent.com/28221425/90212424-e4f00680-de10-11ea-9295-12e36b4e5bcc.jpg)

**FBP**

![157](https://user-images.githubusercontent.com/28221425/90212405-dc97cb80-de10-11ea-9d45-8d3670fd6399.jpg)
--------------------------------------------------------------------------------------------------

**Sino**
 
![ sino 158](https://user-images.githubusercontent.com/28221425/90212449-f6391300-de10-11ea-8bb2-412057eebf91.jpg)

**FBP**

![158](https://user-images.githubusercontent.com/28221425/90212461-fd602100-de10-11ea-9493-bae202bfbabb.jpg)

**Comment by nghia-vo** [comment]
High-frequency features in a sinogram are where there're abrupt changes in intensities. These will be enhanced by the ramp filter in the FBP method resulting streak artifacts. However, the issue with your data is mainly caused by number of projections (height of the sinogram) is small. For direct reconstruction methods (gridrec, FBP), the number of projections should be around the width of the sinogram (http://engineering.purdue.edu/~malcolm/pct/CTI_Ch03.pdf ). For your data, you can try an iterative method, SIRT, with a number of iterations ~ 100-150.
