### ISSUE TITLE
Mapping introduced artifacts

### ISSUE THREAD

**Issue by feketeimre** [nghia-vo/sarepy#7]
When using ring_removal_based_fft and ring_removal_based_wavelet_fft the result gets blurry.
For example when filtering the following **original** image:
![original](https://user-images.githubusercontent.com/15861028/153730841-dac45471-eb65-4e77-958e-81536be3f4a2.png)
The result **filtered** image has the ring artifact correctly removed but the rest of the image is blurry(?):
![filtered](https://user-images.githubusercontent.com/15861028/153730846-5ca60812-1c76-4d05-a63d-1b78ab346864.png)
The **difference** of the above two images clearly shows the problem:
![filtereddiff](https://user-images.githubusercontent.com/15861028/153731622-ae6aea29-6bf7-43d4-a21e-b53a5c1b43cf.png)

If i comment out this line https://github.com/nghia-vo/sarepy/blob/abc540eb692ddcbeb232702247ce70318e4abd4c/sarepy/post/ring_removal_post.py#L230 from the function ring_removal_based_fft, it essentially just maps the image to polar and back to cartesian, but the image still gets blurry. Like this **remapped** image: 
![mappedremapped](https://user-images.githubusercontent.com/15861028/153731176-102709d9-56ad-4333-9c7a-1d7373306eb3.png)
Heres the **difference remapped** image of this and the original. You can see that the image is modified even without the fft or wavelet filtering touching the image:
![mappedremappeddiff](https://user-images.githubusercontent.com/15861028/153731671-4a593034-7294-4079-b80e-21643d00e277.png)

The previous difference remapped image can be removed from the filtered image to get rid of the blurriness but retain the effects of the ring removal by the fft or wavelet. Heres the **result** of this:
![filtereddiffremoved](https://user-images.githubusercontent.com/15861028/153731892-d46cb982-1f92-4c7a-93ed-416d9a534847.png)

The difference of this result image and the original image shows that theres no blur anymore and only the effects of the fft wavelet can be seen:
(This reveals a different problem with the mapping that i dont yet know the solution of and would like to create a new issue later):
![resultdiff](https://user-images.githubusercontent.com/15861028/153731967-fcf610d8-50a8-449d-9a74-e7cd943cc62c.png)

Heres the code for the above images:
```python
import numpy as np
import sarepy.post.ring_removal_post as rrp
import imageio

# modified function to only do mapping and remapping
#def ring_removal_based_fft(mat, u=30, n=8, v=1, pad=150):
def mapremap(mat, u=30, n=8, v=1, pad=150):
    (nrow, ncol) = mat.shape
    if nrow != ncol:
        raise ValueError(
            "Width and height of the reconstructed image are not the same")
    mask = rrp.cirle_mask(ncol, 1.0)
    (xmat, ymat) = rrp.reg_to_polar(ncol, ncol, ncol, ncol)
    (rmat, thetamat) = rrp.polar_to_reg(ncol, ncol, ncol, ncol)
    polar_mat = rrp.mapping(mat, xmat, ymat)
    #polar_mat = srm.remove_stripe_based_fft(polar_mat, u, n, v, pad)
    mat_rec = rrp.mapping(polar_mat, rmat, thetamat)
    return mat_rec * mask

original = imageio.imread('original.png')
#imageio.imwrite('original.png', original)

filtered = rrp.ring_removal_based_fft(original)
imageio.imwrite('filtered.png', filtered)

filtereddiff = filtered - original
imageio.imwrite('filtereddiff.png', numpy.clip(filtereddiff, -15,15))

remapped = mapremap(original)
imageio.imwrite('mappedremapped.png', remapped)

mapremapdiff = remapped-original
imageio.imwrite('mappedremappeddiff.png', numpy.clip(mapremapdiff, -15, 15))

result = filtered - mapremapdiff
imageio.imwrite('filtereddiffremoved.png', result)

resultdiff = result - original
imageio.imwrite('resultdiff.png', numpy.clip(resultdiff, -15,15))
```

Would it be reasonable to fix the two affected functions by removing the effects of the mapping/remapping from the filtered result?

Cheers, 
Imre

**Comment by nghia-vo** [comment]
Hi Imre,
    Thanks for these detailed demonstration. Blurring an image is an expected side-effect of fft-based methods and the polar transformation as informed here: https://sarepy.readthedocs.io/toc/section3.html . The fft-based methods work like low-pass filters (i.e. smoothing filters). The level of blurriness is controlled by the parameter u (fft method) or sigma (wavelet-fft method).  
    
For the polar transformation, the blurriness is caused by the interpolation method  and the sampling ratio. [Here](https://github.com/nghia-vo/sarepy/blob/abc540eb692ddcbeb232702247ce70318e4abd4c/sarepy/post/ring_removal_post.py#L151) I fixed the interpolation function with order =1. In the post-processing methods, the sampling ratio is [selected](https://github.com/nghia-vo/sarepy/blob/abc540eb692ddcbeb232702247ce70318e4abd4c/sarepy/post/ring_removal_post.py#L228) for an output image having the same size as an input image.  To reduce the blurriness you can change the [order of the interpolation method](https://github.com/nghia-vo/sarepy/blob/abc540eb692ddcbeb232702247ce70318e4abd4c/sarepy/post/ring_removal_post.py#L151) or the [sampling ratio](https://github.com/nghia-vo/sarepy/blob/abc540eb692ddcbeb232702247ce70318e4abd4c/sarepy/post/ring_removal_post.py#L58). 

I hope these answers clarify your concern. Out of that, I would recommend to try Algotom where utility methods can provide flexible and convenient ways to test ring removal methods (https://sarepy.readthedocs.io/toc/section5.html). Sarepy will be remained as it is because it's linked with the paper and there's Matlab implementation kindly provided by Daniel.

**Comment by feketeimre** [comment]
> Sarepy will be remained as it is because it's linked with the paper

I understand.
Have a nice day.
